#
# CONFIGURATION
#

# - Each line must contains only one path
# - Comments starts with an hash (#)
# - Enviroment variables will be expanded (ex. '$HOME' -> '/home/...')

#
# EXAMPLE
#

$HOME/.bashrc
